cache:
  paths:
    - benchmarks/

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

before_script:
  - '! [ -e ./benchmarks/dacapo-2006-10-MR2.jar ] && mkdir -p benchmarks && wget https://downloads.sourceforge.net/project/dacapobench/archive/2006-10-MR2/dacapo-2006-10-MR2.jar -O benchmarks/dacapo-2006-10-MR2.jar'

build:pre-commit:
  stage: build
  script:
    - python scripts/testMMTk.py -T pre-commit

build:basebasenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g BaseBaseNoGC

build:basebasesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g BaseBaseSemiSpace -a "Xms75M Xmx75M"
    