cache:
  paths:
    - benchmarks/

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - perf-run
  - perf-check

before_script:
  - '! [ -e ./benchmarks/dacapo-2006-10-MR2.jar ] && mkdir -p benchmarks && wget https://downloads.sourceforge.net/project/dacapobench/archive/2006-10-MR2/dacapo-2006-10-MR2.jar -O benchmarks/dacapo-2006-10-MR2.jar'

build:pre-commit:
  stage: build
  script:
    - python scripts/testMMTk.py -T pre-commit

build:rbasebasenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g RBaseBaseNoGC

build:rfastadaptivenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g RFastAdaptiveNoGC

build:rfulladaptivenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g RFullAdaptiveNoGC

build:basebasenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g BaseBaseNoGC

build:rbasebasesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g RBaseBaseSemiSpace

build:rfastadaptivesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g RFastAdaptiveSemiSpace

build:rfulladaptivesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g RFullAdaptiveSemiSpace

build:basebasesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g BaseBaseSemiSpace

perf-run:
  stage: perf-run
  script:
    - .ci/perf-run.sh
  artifacts:
    paths:
      - .ci/running/results/log

perf-check:BaseBaseNoGC:
  stage: perf-check
  script:
    - python .ci/perf-check.py BaseBaseNoGC
  dependencies:
    - perf-run
