cache:
  paths:
    - benchmarks/

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - perf-run
  - perf-check

before_script:
  - '! [ -e ./benchmarks/dacapo-2006-10-MR2.jar ] && mkdir -p benchmarks && wget https://downloads.sourceforge.net/project/dacapobench/archive/2006-10-MR2/dacapo-2006-10-MR2.jar -O benchmarks/dacapo-2006-10-MR2.jar'

build:pre-commit:
  stage: build
  script:
    - python scripts/testMMTk.py -T pre-commit

build:rbasebasenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g RBaseBaseNoGC

build:rfastadaptivenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g RFastAdaptiveNoGC
  artifacts:
    paths:
      - dist/RFastAdaptiveNoGC_x86_64-linux

build:fastadaptivenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g FastAdaptiveNoGC --build-only
  artifacts:
    paths:
      - dist/FastAdaptiveNoGC_x86_64-linux

build:rfulladaptivenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g RFullAdaptiveNoGC

build:basebasenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g BaseBaseNoGC

build:rbasebasesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g RBaseBaseSemiSpace

build:rfastadaptivesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g RFastAdaptiveSemiSpace

build:rfulladaptivesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g RFullAdaptiveSemiSpace

build:basebasesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g BaseBaseSemiSpace

perf-run:
  stage: perf-run
  script:
    - git clone git@gitlab.anu.edu.au:plsl/tools/running.git .ci/running -b rust-mmtk
    - ln -s "$(realpath dist)" .ci/running/build
    - cp .ci/RunConfig.pm .ci/running/bin/RunConfig.pm
    - mkdir -p .ci/running/bin/probes
    - cp .ci/probes.jar .ci/running/bin/probes/probes.jar
    - .ci/running/bin/runbms 16 16
  artifacts:
    paths:
      - .ci/running/results/log

NoGC:
  stage: perf-check
  script:
    - python .ci/perf-check.py FastAdaptiveNoGC
  dependencies:
    - perf-run
